### ISSUE TITLE
Incoming RPC 106

### ISSUE THREAD

**Issue by Zelyutin** [BrunoBM16/samp-packet-list#12]
Hi!

You have 106 RPC in Outcoming section.
UpdateVehicleDamageStatus - ID: 106
> Parameters: UINT16 wVehicleID, UINT32 panels, UINT32 doors, UINT8 lights, UINT8 tires

It also appears as incoming RPC when player makes damage to the vehicle.
Parameters are the same.

**Comment by BrunoBM16** [comment]
Added, thank you.
