### ISSUE TITLE
Addition for driver sync

### ISSUE THREAD

**Issue by Zelyutin** [BrunoBM16/samp-packet-list#15]
At the end of driver sync now we have FLOAT train_speed.
But actually it's not just train speed. I'd rather name it ExtraData
It can contain following values in it's 32 bits:  
- FLOAT Train Speed for train
- FLOAT Bike Incline for bikes
- Uint16+Uint16 Hydra Thrust Angle (It seems that only first is useful, but second is not always zero).

Hydra thrust can be found here:
https://github.com/IllidanS4/YSF/blob/0a454418db50b5be14fcd75b4370599170cf9fdd/src/Structs.h#L331
https://github.com/IllidanS4/YSF/blob/c15389a39d3d20d26711704f66c7a6652a2f5e4e/src/natives/players.cpp#L509

**Comment by Zorono** [comment]
@urShadow

**Comment by NexiusTailer** [comment]
Fixed, thank you.
