### ISSUE TITLE
Wrong type of wListItem in RPC SendDialogResponse

### ISSUE THREAD

**Issue by NexiusTailer** [BrunoBM16/samp-packet-list#20]
SendDialogResponse have wListItem parameter with the type UINT16, but listitem wich passed in public OnDialogResponse can have negative values (-1 if the responsed dialog isn't in the style list), while UINT16 in this case will have 65535.

**Comment by Zelyutin** [comment]
-1 would be 65535 for uint16, it's just the presentation issue.

**Comment by Zelyutin** [comment]
Didn't get your suggestion first. Yes, INT16 may looks better for this parameter.

**Comment by BrunoBM16** [comment]
Changed.

Thanks.
