### ISSUE TITLE
Wrong type of wPlayerID parameter in RPC SetPlayerSkin

### ISSUE THREAD

**Issue by NexiusTailer** [BrunoBM16/samp-packet-list#21]
It seems that wPlayerID should have UINT32 type, not UINT16, as with this type it doesn't work.

**Comment by NexiusTailer** [comment]
UPD: Related to #14

**Comment by VenomSA** [comment]
BrunoBM16 is there any way I can contact you privately?

**Comment by BrunoBM16** [comment]
@VenomSA You can contact me on Discord: BrunoBM16#8452

**Comment by NexiusTailer** [comment]
@BrunoBM16 What about some changes?

**Comment by BrunoBM16** [comment]
That is 0.3.DL specific. Edited anyway: https://github.com/BrunoBM16/samp-packet-list/wiki/0.3.DL-Specific-RPCs#setplayerskin---id-153

Thanks for reporting, I will be handling the other issues I should have looked at previously.

**Comment by NexiusTailer** [comment]
@BrunoBM16 it seems the issue keeps existing as UINT32 it's not only about 0.3.DL, it is right type for 0.3.7 as well.
