### ISSUE TITLE
Make investigated argument types in Pawn.RakNet PR_ format

### ISSUE THREAD

**Issue by NexiusTailer** [BrunoBM16/samp-packet-list#25]
Since the main benefit of this wiki is for pawn scripters who need the packet arguments and their data types to access from Pawn.RakNet plugin, it would be wise to document them according to the types that are available in this plugin: PR_UINT8, PR_INT16, PR_FLOAT, PR_BITS etc.

**Comment by ADRFranklin** [comment]
I don't think this repo was specifically aimed for pawn scripters. It's more useful for plugin developers or developers that create software to work with sa-mp.

For example open.mp, uses this repo a lot for working with sa-mp packet structures. So I feel it's a little selfish to want it in a single format for a specific plugin.

The current wiki, shows it in a state that easily understandable by any developer or works with packets in general, which is how it should be represented.

**Comment by NexiusTailer** [comment]
Ah, ok, I just didn't know that it is also widely useful for other people here
