### ISSUE TITLE
Incorrect parameter type in RPC TogglePlayerSpectating

### ISSUE THREAD

**Issue by NexiusTailer** [BrunoBM16/samp-packet-list#26]
It seems that "spectating" param must be UINT32, not UINT8.

**Comment by Gedwadion** [comment]
@NexiusTailer, странно, что так много выделено под этот RPC. Но естественно не <= 127

**Comment by BrunoBM16** [comment]
Hey guys, I haven't updated the list for a while. I guess it is time to get new maintainers.

@NexiusTailer are you interested?

Thanks.

**Comment by NexiusTailer** [comment]
Yes, I'm currently working on a new protection that very closely relies on sync hooking and I have an interest in adding all the found information here.  But I think it’s wise to also find people who have some reverse engineering skills to clarify some inaccuracies and controversial situations, if any will appear.

**Comment by BrunoBM16** [comment]
Right.

I have sent you an invitation.

**Comment by NexiusTailer** [comment]
Thanks you, now I fixed this issue too.
