### ISSUE TITLE
RPC 44 doubt

### ISSUE THREAD

**Issue by HarryPotterTroll** [BrunoBM16/samp-packet-list#27]
Hi, I was getting Outcoming RPC 44 params, but when I got AttachVehicle ID (65535), it was greater than 2000 (Max vehicle id).
Do you know how I could get 0-2000 Vehicle ID?

**Comment by NexiusTailer** [comment]
RPC 44 = CreateObject. 65535 = INVALID_VEHICLE_ID in your case.
You probably didn't attach your object to any vehicle, so that this value is passed.
