### ISSUE TITLE
ShowTextDraw szTextLen, flags, global vs player

### ISSUE THREAD

**Issue by yugecin** [BrunoBM16/samp-packet-list#28]
- `szTextLen` is typed as `UINT8` but it's a `UINT16`
- Here are some values of the `Flags` field:
  - bit 1: box on/off
  - bit 2: align left
  - bit 3: align center
  - bit 4: align right
  - bit 5: proportional font on/off
- Might be worthwhile to note that global textdraws use id 0-2047 and per-player use id 2048-2303

**Comment by NexiusTailer** [comment]
Thank you for the corrections and additional info, updated.
