### ISSUE TITLE
Outcoming RPCs 26 & 154

### ISSUE THREAD

**Issue by Zelyutin** [BrunoBM16/samp-packet-list#7]
Hi!

There's RPC EnterVehicle - 26 and ExitVehicle - 154 in Incoming RPC list.
But there's no Outcoming versions of them.

So, it's **PlayerEnterVehicle - 26**

> Parameters: UINT16 wPlayerID, UINT16 wVehicleID, UINT8 bIsPassenger

> Additional Information: if bIsPassenger is 0, the player is about to enter the driver seat. If bIsPassenger is 1, the player is about to enter any of the passenger seats in the vehicle.

and **PlayerExitVehicle - 154**

> Parameters: UINT16 wPlayerID, UINT16 wVehicleID

**Comment by BrunoBM16** [comment]
Thanks for informing, added to the list.
